quarkus:
  http:
  #    port: 8082
#  smallrye-openapi:
#    info-title: order-svc
#    auto-add-security-requirement: false
#
#  swagger-ui:
#    always-include: true
#    path: /swagger
#

  datasource:
    db-kind: postgresql
    jdbc:
      url: ${EMISSION_DB_URL}
    username: ${EMISSION_DB_USERNAME}
    password: ${EMISSION_DB_PASSWORD}
    slave:
      db-kind: postgresql
      jdbc:
        url: ${EMISSION_DB_SLAVE_URL}
      username: ${EMISSION_DB_SLAVE_USERNAME}
      password: ${EMISSION_DB_SLAVE_PASSWORD}

    transaction-manager:
      default-transaction-timeout: 300s
  hibernate-orm:
    database:
      generation: none

